language: node_js
node_js:
  - 0.10
  - 0.11
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install pkg-config cmake openssl libc-ares-dev
  - wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
  - tar xzf mosquitto-1.3.1.tar.gz
  - cd mosquitto-1.3.1
  - cmake .
  - sudo make install
