language: node_js
node_js:
  - 0.10
  - 0.11
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mosquitto
  - sleep 10
